sudo: required

language: node_js
node_js:
  - "10"
  - "node"
services:
  - docker
before_install:
  - cp .env.dist .env
  - npm i -g npm@latest
  - npm i -g yarn
install:
  - docker-compose up -d
  - yarn
script:
  - yarn run test
after_success: yarn run coveralls
